- hosts: publicVMS
  become: true
  vars:
    LOADBALNCERIP: __LOADBALNCERIP__
    OKTAORGIL: __OKTAORGIL__
    OKTACLIENTID: __OKTACLIENTID__
    OKTACLIENTSECRET: __OKTACLIENTSECRET__
    PGHOST: __PGHOST__
    PGUSERNAME: __PGUSERNAME__
    PGDATABASE: __PGDATABASE__
    PGPASSWORD: __PGPASSWORD__

  tasks:
    - name: Install curl & git packages
      apt:
        name:
          - curl
          - git

        update_cache: yes

    - name: install node version 14
      become: true
      shell: curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash - && sudo apt-get install -y nodejs

    - name: copy my file
      synchronize:
        src: /home/Itzik/Itzik/myagent/_work/r1/a
        dest: /home/Itzik/bootcamp

    - name: Install WebApp JS Package
      ansible.builtin.shell:
        chdir: /home/Itzik/bootcamp/a/_weightapp-ar
        cmd: npm install

    - name: install nodemon
      become: true
      ansible.builtin.shell: cd /home/Itzik/bootcamp/a/_weightapp-ar/ "npm install --save-dev nodemon@2"

    - name: Creating a file with content
      copy:
        dest: "/home/Itzik/bootcamp/a/_weightapp-ar/.env"
        content: |
          ###
          PORT=8080
          ###internal ip addrass of the vm
          HOST={{ ansible_default_ipv4.address }}
          NODE_ENV=development

          ###extrnal host url
          HOST_URL={{ LOADBALNCERIP }}

          COOKIE_ENCRYPT_PWD=superAwesomePasswordStringThatIsAtLeast32CharactersLong!
          ### Okta configuration
          OKTA_ORG_URL={{ OKTAORGIL }}
          OKTA_CLIENT_ID={{ OKTACLIENTID }}
          OKTA_CLIENT_SECRET={{ OKTACLIENTSECRET }}
          ### Postgres configuration
          ###internal db server ip
          ###should be server name
          PGHOST={{ PGHOST }}
          PGUSERNAME={{ PGUSERNAME }}
          PGDATABASE={{ PGDATABASE }}
          PGPASSWORD={{ PGPASSWORD }}
          PGPORT=5432

    - name: Initalize App's Database
      ansible.builtin.shell:
        chdir: /home/Itzik/bootcamp/a/_weightapp-ar/
        cmd: npm run initdb

    - name: install pm2
      become: true
      command: "sudo npm install pm2@latest -g"
 
    - name: pm2 startup
      become: true
      command: "pm2 startup"
 
   - name: pm2 to startup
     become: true
     command: sudo env PATH=$PATH:/usr/bin /usr/lib/node_modules/pm2/bin/pm2 startup systemd -u Itzik --hp /home/Itzik

   - name: run app
     command: "pm2 start 'npm run dev'"
     args:
       chdir: /home/Itzik/bootcamp/a/_weightapp-ar/
    
    - name: save app in pm2 startup state
      become: true
      command: "pm2 save"