---
- hosts: publicVMS
  vars_files:
    - /etc/ansible/vars.yml
  tasks:
    - name: install node version 14
      become: true
      shell: curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash - && sudo apt-get install -y nodejs

    - name: Clone a github repository
      git:
        repo: https://github.com/ItzikEzra/bootcamp-app.git
        dest: ~/bootcamp
        clone: yes
        update: yes

    - name: Write .env file
      shell: |
        echo 'PORT=8080
        #internal ip addrass of the vm
        HOST={{ ansible_default_ipv4.address }}
        NODE_ENV=development

        #extrnal host url
        HOST_URL= {{ load_balncer_ip }}
        COOKIE_ENCRYPT_PWD=superAwesomePasswordStringThatIsAtLeast32CharactersLong!

        # Okta configuration
        OKTA_ORG_URL="{{okta_org_url}}"
        OKTA_CLIENT_ID={{okta_client_id}}
        OKTA_CLIENT_SECRET={{okta_client_secret}}
        # Postgres configuration
        #internal db server ip
        #should be server name
        PGHOST={{pghost}}
        PGUSERNAME={{pgusername}}
        PGDATABASE={{pgdatabase}}
        PGPASSWORD={{pgpassword}}
        PGPORT=5432' >>~/bootcamp/.env
